Admin\ContactBundle\Entity\Message:
    type: entity
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        name:
            type: string
        email:
            type: string
        message:
            type: text
        timeSent:
            type: datetime
        status:
            type: integer
