Perform\ContactBundle\Entity\Message:
    type: entity
    table: perform_contact_message
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        name:
            type: string
        email:
            type: string
        message:
            type: text
        status:
            type: integer
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToMany:
        spamReports:
            targetEntity: Perform\SpamBundle\Entity\Report
            joinTable:
                name: perform_contact_message_spam_reports
            cascade:
                - persist
