Perform\ContactBundle\Entity\SpamReport:
    type: entity
    table: perform_contact_spam_report
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        type:
            type: string
        ip:
            type: string
        userAgent:
            type: string
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
    manyToOne:
        message:
            targetEntity: Perform\ContactBundle\Entity\Message
            joinColumn:
                nullable: false
            
