services:
    admin_contact.admin.message:
        class: Admin\ContactBundle\Admin\MessageAdmin
        tags:
            - { name: admin_base.admin, entity: "AdminContactBundle:Message" }

    admin_contact.menu_link.contact:
        class: Admin\ContactBundle\Menu\ContactLinkProvider
        tags:
            - { name: admin_base.link_provider, alias: contact }

    admin_contact.form.handler.contact:
        class: Admin\ContactBundle\Form\Handler\ContactFormHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@admin_notification.notifier"
            - "@admin_notification.provider.settings"
            - "@logger"
