services:
    perform_contact.crud.message:
        class: Perform\ContactBundle\Crud\MessageCrud
        tags:
            -
                name: perform_base.crud
                crud_name: "perform_contact.message"
                list_context: "/"
                view_context: "/view/{id}"


    perform_contact.menu_link.contact:
        class: Perform\BaseBundle\EventListener\SimpleMenuListener
        arguments:
            - 'contact'
            - 'perform_contact.message'
            - null
            - 'envelope'
        tags:
            - { name: kernel.event_listener, event: perform_base.menu.build, method: onMenuBuild }

    perform_contact.form.handler.contact:
        class: Perform\ContactBundle\Form\Handler\ContactFormHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@perform_notification.notifier"
            - "@perform_notification.provider.settings"
            - "@perform_spam.manager"
            - "@logger"

    perform_contact.panel.messages:
        class: Perform\ContactBundle\Panel\MessagesPanel
        arguments:
            - "@perform_base.doctrine.entity_resolver"
            - "@doctrine.orm.entity_manager"
            - "@twig"

    perform_contact.settings.contact_form:
        class: Perform\ContactBundle\Settings\ContactFormPanel
        tags:
            - { name: perform_base.settings_panel, alias: contact_form }

    perform_contact.action.archive:
        class: Perform\ContactBundle\Action\ArchiveAction
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: perform_base.action, alias: perform_contact_archive }

    perform_contact.action.new:
        class: Perform\ContactBundle\Action\NewAction
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: perform_base.action, alias: perform_contact_new }

    perform_contact.action.spam:
        class: Perform\ContactBundle\Action\SpamAction
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: perform_base.action, alias: perform_contact_spam }

    Perform\ContactBundle\Command\:
        resource: '../../Command'
        public: false
        autowire: true
        autoconfigure: true
