services:
    perform_contact.admin.message:
        class: Perform\ContactBundle\Admin\MessageAdmin
        tags:
            - { name: perform_base.admin, entity: "PerformContactBundle:Message" }

    perform_contact.menu_link.contact:
        class: Perform\BaseBundle\Menu\SimpleLinkProvider
        arguments:
            - 'contact'
            - 'PerformContactBundle:Message'
            - null
            - 'envelope'
        tags:
            - { name: perform_base.link_provider, alias: contact }

    perform_contact.form.type.honeypot:
        class: Perform\ContactBundle\Form\Type\HoneypotType
        arguments:
            - "@event_dispatcher"
        tags:
            - { name: form.type }

    perform_contact.spam_checker.honeypot:
        class: Perform\ContactBundle\SpamChecker\HoneypotChecker
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@logger"
        tags:
            - { name: kernel.event_listener, event: perform_honeypot_caught, method: onHoneypotCaught }

    perform_contact.form.handler.contact:
        class: Perform\ContactBundle\Form\Handler\ContactFormHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@perform_notification.notifier"
            - "@perform_notification.provider.settings"
            - "@logger"
        calls:
            - [addSpamChecker, ['@perform_contact.spam_checker.honeypot']]

    perform_contact.panel.messages:
        class: Perform\ContactBundle\Panel\MessagesPanel
        arguments:
            - "@perform_base.doctrine.entity_resolver"
            - "@doctrine.orm.entity_manager"
            - "@twig"

    perform_contact.settings.contact_form:
        class: Perform\ContactBundle\Settings\ContactFormPanel
        tags:
            - { name: perform_base.settings_panel, alias: contact_form }

    perform_contact.action.archive:
        class: Perform\ContactBundle\Action\ArchiveAction
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: perform_base.action, alias: perform_contact_archive, entity: 'PerformContactBundle:Message' }

    perform_contact.action.new:
        class: Perform\ContactBundle\Action\NewAction
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: perform_base.action, alias: perform_contact_new, entity: 'PerformContactBundle:Message' }

    perform_contact.action.spam:
        class: Perform\ContactBundle\Action\SpamAction
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: perform_base.action, alias: perform_contact_spam, entity: 'PerformContactBundle:Message' }

    Perform\ContactBundle\Command\:
        resource: '../../Command'
        public: false
        autowire: true
        autoconfigure: true
